# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A Development Blog
tagline:          'A Jekyll theme'
description:      'I love coding and its about time I start writing about it.'
url:              http://matthewtrask
baseurl:          /

author:
  name:           'Matt Trask'
  url:            https://twitter.com/matthewtrask

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://github.com/rocketpastsix
