# Site settings
title: A Developer Blog
email: mjftrask@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Im a developer who is passionate about learning, open source and pushing yourself to the limits.
baseurl: "" # the subpath of your site, e.g. /old_blog/
url: "http://matthewtrask.me" # the base hostname & protocol for your site
permalink: pretty
encoding: "utf-8"




twitter_username: matthewtrask
github_username:  rocketpastsix


# Build settings
markdown: kramdown
permalink: /:title

#Comments
comments:
  provider: disqus
  disqus:
    short_name: matthewtrask

#analytics
analytics:
  provider: Google
  google:
    tracking_id :
