title: Matt Trask
description: My travels from the start to now.

url: http://matthewtrask.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Talks
   url: /talks
 - title: Contact
   url: /contact
 - title: Purpose
   url: /purpose

social:
   github: rocketpastsix
   twitter: matthewtrask
   email: mjftrask@gmail.com

comments :
  provider : disqus
  disqus :
    short_name : matthewtrask

google_analytics: "UA-64167405-1"
