title: Matt Trask
description: My travels from the start to now.

url: http://matthewtrask.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: rocketpastsix
   twitter: matthewtrask
   email: mjftrask@gmail.com

google_analytics: ""
